# docker-compose.yml
version: '3.8'

services:
  php:
    container_name: php-cli-1
    build:
      context: ./api
    volumes:
      - ./api:/var/www/html
      - ./api/public:/var/www/html/public
    networks:
      - app_network

  nginx:
    container_name: nginx-1
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: db-1
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app_network
  frontend:
    container_name: frontend-1
    build:
      context: ./frontend
    ports:
      - "8081:80" # Adjusted to use port 8081 on the host
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  database_data:
